### ISSUE TITLE
Not all the selected items are being carried across from screen 3 to screen 4

### ISSUE THREAD

**Issue by BlinkyBill62** [CLOSER-Cohorts/Equivalences#1]
![Page 3 - 1](https://user-images.githubusercontent.com/51624515/108695567-56172180-74f8-11eb-820b-1f7dbcf35230.jpg)
![Page 4 - 1](https://user-images.githubusercontent.com/51624515/108695580-5ca59900-74f8-11eb-9287-b8768f62f1fd.jpg)

**Comment by HayleyMills** [comment]
Tested this, and it appears to be displaying all selected variables on the next page.
