### ISSUE TITLE
Loading csv doesn't load all items

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#11]
I loaded in this csv which has 200 items, but it only loads up 188, loading 189 in a stange way. 
[display.txt](https://github.com/CLOSER-Cohorts/Equivalences/files/6147627/display.txt)

![image](https://user-images.githubusercontent.com/16664703/111286331-fe249400-8639-11eb-8665-12b02c29f6bd.png)

![image](https://user-images.githubusercontent.com/16664703/111286413-15fc1800-863a-11eb-9bcb-6b8b3c025e98.png)

![image](https://user-images.githubusercontent.com/16664703/111286563-3c21b800-863a-11eb-938c-1cb144b0c15f.png)

![image](https://user-images.githubusercontent.com/16664703/111286698-5eb3d100-863a-11eb-8029-b170818b8d9e.png)

**Comment by BlinkyBill62** [comment]
I checked the file again and it loads all 200. Can you give another go

**Comment by HayleyMills** [comment]
Reloaded display.csv and it is now loading in 200 items.
