### ISSUE TITLE
Selected sweep ALSPAC early adulthood, Match Text, Match Text, equivalent questions and receive an error

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#12]
I receive an error after 30+ minutes, I have tried this several times. 
Error.
An error occurred while processing your request.

**Comment by BlinkyBill62** [comment]
There was an additional issue with saving CSV due to the number of equivalences. This should now be addressed and needs testing.

**Comment by HayleyMills** [comment]
Great, this is now working.
