### ISSUE TITLE
Add topic/concept filter on select page

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#19]
Would it be possible in addtion to being able to select the studies/sweeps on the select page - to also be able to reduce the number of results by selecting a level 1 topic?

**Comment by BlinkyBill62** [comment]
It may be possible to achieve this but there are problems associated with doing this as we do not know the appropriate topic/concept for the selected studies/sweeps at this stage. I have implemented a different way to do this. I have added a drop box on the display page which allows selection of topic/concept from the equivalences. This has the advantage of allowing to look at variety of topics/concepts without loading the data again. It works a little slower but means we never lose any equivalences.

This seems a better solution but needs to be evaluated by Hayley to see if this is fit for purpose.

**Comment by HayleyMills** [comment]
This has been added, and allows for the equivelancies list to be filtered to specific topics, in order to reduce overwhelm.
