### ISSUE TITLE
Names and text are not being carried over to the next page

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#2]

**Comment by HayleyMills** [comment]
Tested this and the description is now being carried over, but the Name is still using the default? e.g. Same Text 1 

![image](https://user-images.githubusercontent.com/16664703/110511165-de521500-80fb-11eb-8f67-3ae7015400fa.png)

In addition, the csv download of this page has Search Term and Description, but no name. 
[waves.xlsx](https://github.com/CLOSER-Cohorts/Equivalences/files/6110311/waves.xlsx)

**Comment by HayleyMills** [comment]
Tested and the Name id now carrying accross pages.

**Comment by HayleyMills** [comment]
This seems to be happening again? I have changed the names, but they revert back on the next page?

**Comment by BlinkyBill62** [comment]
I believe this has been addressed but needs verification

**Comment by HayleyMills** [comment]
Tested and this is now working.
