### ISSUE TITLE
Unticked items are being carried over to the next page

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#25]
I selected HCS waves 1 and 2 matching questions by text. I unticked a couple of items (ID 4), but they still remained on the next page.  
[All_hcs_1,2.csv](https://github.com/CLOSER-Cohorts/Equivalences/files/7092702/All_hcs_1.2.csv)
[Display_hcs_1,2.csv](https://github.com/CLOSER-Cohorts/Equivalences/files/7092705/Display_hcs_1.2.csv)

**Comment by BlinkyBill62** [comment]
I believe this issue to be addressed now but needs verification

**Comment by HayleyMills** [comment]
This is now working.
