### ISSUE TITLE
Cannot delete words from the "Add word(s) to search" list

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#28]
You can add words (single, or sets of three comma seperated) in the text box, however, if you want to to remove any of these, you receive the error:

Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.

Requested URL: /Equivalence/Equivalences

**Comment by BlinkyBill62** [comment]
I have tested the source of this error and believe I have rectified this, but needs more testing. If you add more than one word and save it will create a single equivalence with all the words. If you add more than one word separated by a comma it will add each word as a separate equivalence

**Comment by HayleyMills** [comment]
This is now working as described above.

**Comment by HayleyMills** [comment]
When I've tried this again -clicking delete goes to an error page

Error.
An error occurred while processing your request.
