### ISSUE TITLE
The fourth result page is not loading

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#3]

**Comment by HayleyMills** [comment]
The following pages load: 
1 select
2 display (tick)
3 variables (add names)
4 waves (columns by waves)
5 dataset (columns by datasets)
Pages 1-5 are now loading. But the sixth page is not loading?

**Comment by HayleyMills** [comment]
Is there a 6th page? As it is still not loading- it takes you back to the first page?

**Comment by BlinkyBill62** [comment]
There is no 6th page and goes back to the first page. Works as a loop so you can do multiple equivalences. I change Next button to Start if that is better

**Comment by HayleyMills** [comment]
@BlinkyBill62 Yes I think would be helpful, so uo know you have reached the end. Maybe "Restart" or "Done"

**Comment by HayleyMills** [comment]
This has now been updated.
