### ISSUE TITLE
Redesign the first page to it is less confusing

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#43]
@spuddybike will draft a design which clearly shows which section you are in, and only displays the the options which are relevant.

**Comment by BlinkyBill62** [comment]
This has been completed and needs to be checked to make sure it meets requirements.

**Comment by HayleyMills** [comment]
I don't have notes from the meeting about this, but it is a lot better having the options along the top. I'll test out each of the options. So far, the Search Repository looks good to me. I'll test the others. 

I would like a button on most of the pages to reset and return to the home page please.

**Comment by HayleyMills** [comment]
The only page which is confusing now if the Upload Equivalences File page. I'm not sure what the these buttons are?
![image](https://user-images.githubusercontent.com/16664703/216666786-066de6fc-6f08-45d1-babf-ec51d14b283a.png)

**Comment by BlinkyBill62** [comment]
Should be done pending Hayley checking against Issue #40

**Comment by HayleyMills** [comment]
Additional buttons have now been removed.
