### ISSUE TITLE
Moving through Next and Previous buttons

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#44]
When on the Display- Equivalences page and select a concept then next, when you go back it has all the items (which is fine) but they are all unticked?

**Comment by BlinkyBill62** [comment]
Minor change - max 10 mins

**Comment by BlinkyBill62** [comment]
Max 30 mins to 1 hr

**Comment by BlinkyBill62** [comment]
I have made changes and tested this repeatedly. If still does not work the way it should. Please arrange a meeting to discuss.

**Comment by HayleyMills** [comment]
This is now working, when I untick some items, and move Next, when I go to Previous it has retained that information.
