### ISSUE TITLE
List what has been searched/selected

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#46]
At the top of the equivalences page can it include what was searched/selected? e.g. Search match on X and X on Study X and Sweeps X

**Comment by BlinkyBill62** [comment]
Change has been done but need to know if this is what is required.

**Comment by HayleyMills** [comment]
This looked good, but it is missing whether it is matching on questions and variables.

**Comment by BlinkyBill62** [comment]
Just need add matching question or variables - 20 mins

**Comment by BlinkyBill62** [comment]
This has been done but not uploaded to server for review
