### ISSUE TITLE
Changing concepts Error. An error occurred while processing your request

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#49]
Selected
o	Usoc covid waves
o	Match All Words
o	Match Text
o	Equivalent variables

Changed the concepts which were incorrect using the drop down list. I did this for all questions/variables I wanted to change the concept and left the ones which did not need changing. I then clicked on Update

**Comment by BlinkyBill62** [comment]
This did not work on Friday and returned an error
I tried it on Tuesday and seems fine now.

**Comment by HayleyMills** [comment]
Thanks @BlinkyBill62, I tried again and it worked. I'll send you the csv so you can use it to test the change groups.
