### ISSUE TITLE
Need to click the studies/sweep before you click pattern matching otherwise the additional options don’t show. 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#50]
Include in instructions.

**Comment by BlinkyBill62** [comment]
On the Search Repository option it does display the following message

Please select the Studies for Equivalences first

If this is inadequate I could try to it that it will not display any selections until study or studies are selected.
If this needs to be specified in the documentation on the wiki. Currently no detailed documentation exists.

**Comment by HayleyMills** [comment]
Okay thanks!
