### ISSUE TITLE
Error after Upload Studies file

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#52]
- I clicked on Upload Studies File
- I chose the file which was saved as per #51 
- Clicked Upload Studies
Received the error 

Error.
An error occurred while processing your request.

[display_output_all_us_covid_match_words_text_variables.csv](https://github.com/CLOSER-Cohorts/Equivalences/files/10661801/display_output_all_us_covid_match_words_text_variables.csv)

**Comment by BlinkyBill62** [comment]
There is an issue in getting variable concepts for variables. Cannot see reason. Could take 2 hrs hopefully

**Comment by BlinkyBill62** [comment]
This issue should have been addressed and uploaded for testing

**Comment by HayleyMills** [comment]
Tested as above and the file loads and displays the equivalences.
