### ISSUE TITLE
Error after Upload Equivalences File

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#53]
- I clicked on upload Equivalences File
- I chose the file which was saved as per #51 
- Clicked Upload 
- Received the error

Error.
An error occurred while processing your request.

[display_output_equivalences_us_covid_match_words_text_variables.csv](https://github.com/CLOSER-Cohorts/Equivalences/files/10661798/display_output_equivalences_us_covid_match_words_text_variables.csv)

**Comment by BlinkyBill62** [comment]
There is an issue in getting variable concepts for variables. Cannot see reason. Could take 2 hrs hopefully
Same issue as issue #52 so resolve one will resolve other

**Comment by BlinkyBill62** [comment]
This should have been addressed and uploaded for testing

**Comment by HayleyMills** [comment]
Tested as above and the file loads and displays.
