### ISSUE TITLE
Minor text change

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#56]
"Upload Equivalences" is confusing as there is already an Upload Equivalences at the top level. Can we change this to 'Use word list'. This covers both uploading and typing in the words. 

![image](https://user-images.githubusercontent.com/16664703/225325601-8b26f7ab-6f35-4bc3-a280-8a4280574e0a.png)

**Comment by HayleyMills** [comment]
Upload equivalences select has been updated to Use word List, but the button hasn't. 
![image](https://user-images.githubusercontent.com/16664703/226633195-6d1a56ad-cf39-4e0d-a0dc-13a325f92ccd.png)

**Comment by BlinkyBill62** [comment]
This has now been modified so the button also shows 'Upload Word List'

**Comment by HayleyMills** [comment]
Great thanks.
