### ISSUE TITLE
What should the Save CSV do?

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#6]

**Comment by BlinkyBill62** [comment]
When a user presses the save csv it will create a csv in the users download directory. The four file names are Display, Variables, Waves and Datasets. When it has finished creating a file it will display at the bottom of the browser.

**Comment by HayleyMills** [comment]
CSVs are now downloading on each page and the display.csv can be uploaded on the select page and reloaded.
