### ISSUE TITLE
Would it be possible to flag which sets of variables/questions don't have the same topic/concept?

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#7]

**Comment by BlinkyBill62** [comment]
Create a new page that will display either only equivalences where there is more than one concept or highlight equivalences where there is more than one concept. This new page will appear before the display page. There will be a selection box to select items to be processed. Once all items to be processed are selected generate a csv which will be used to update these items using the SDK.

**Comment by HayleyMills** [comment]
This works well. I think it would be useful to have the question text and variable text on this page, as otherwise it is hard to make a judgement about which topic/concept to choose.

**Comment by BlinkyBill62** [comment]
I have added question text and variable text to this page. They are found by scrolling right. Discussion may be useful on what columns should be displayed on this page.

**Comment by HayleyMills** [comment]
This has now been added, can we move the non important (for users) ID columns to the end please? i.e Question Item, Question Concept, Variable Item and Variable Concept.

**Comment by BlinkyBill62** [comment]
I have changed the order of the items displayed on this screen as suggested. This needs verification and if necessary more changes.
